---
- name: My demo playbook
  hosts: "*"

  tasks:
  - name: Creating first directory
    file: path=/var/tmp/manojsir state=directory

  - name: Creating a file inside Manoj Sir directory
    file: path=/var/tmp/manojsir/testingfile state=touch
