---
- name: This is my NTP Playbook
  hosts: "*"
#  become: root
  

  tasks:
  -  name: Installing NTP Package
     yum: name=ntp state=present

  -  name: Creating file
     file: path=/etc/ntp.conf state=file

  -  name: Starting and Enabling Service Across reboots
     service: name=ntpd state=started enabled=yes
...
